name: Mod and Build

on:
  push:
    branches:
      - main

jobs:
  modify_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Android SDK
        uses: actions/setup-android@v2
        with:
          sdk-platform: '30' # Adjust to the platform version you need
          build-tools: '30.0.3' # Use a version that includes zipalign

      - name: Install apktool
        run: |
          wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O $HOME/apktool
          wget https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar -O $HOME/apktool.jar
          chmod +x $HOME/apktool
          sudo mv $HOME/apktool /usr/local/bin/
          sudo mv $HOME/apktool.jar /usr/local/bin/

      - name: Decompiling APK
        run: apktool d dynamicspot-latest.apk -o decompiled_apk

      - name: Modify smali file
        run: python modify.py

      - name: Recompile APK
        run: apktool b decompiled_apk -o dynamicspot-modded.apk

      - name: Generate debug.keystore
        run: |
          keytool -genkeypair -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -keystore debug.keystore -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"

      - name: Sign APK with debug key
        run: jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore debug.keystore -storepass android -keypass android dynamicspot-modded.apk androiddebugkey

      - name: Align APK
        run: $ANDROID_HOME/build-tools/30.0.3/zipalign -v 4 dynamicspot-modded.apk dynamicspot-modded-aligned.apk

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: DynamicSpot-Modded.apk
          path: ./dynamicspot-modded-aligned.apk
